Repository Team-CrowdZero/CrowdZero-Android, pull requests merged in 2025-02, with the labels that each got.

#6 [Feature/#3] : 장소 상세 UI 구현
  app/src/main/java/com/gdg/crowdzero_android/main/MainScreen.kt
  app/src/main/java/com/gdg/crowdzero_android/navigation/DetailNavigation.kt
  core/build.gradle.kts
  core/src/main/java/com/gdg/core/designsystem/component/bar/CongestionBar.kt
  core/src/main/java/com/gdg/core/designsystem/component/chip/FineDustChip.kt
  core/src/main/java/com/gdg/core/designsystem/theme/Color.kt
  core/src/main/java/com/gdg/core/type/CongestionType.kt
  core/src/main/java/com/gdg/core/type/DustConditionType.kt
  core/src/main/java/com/gdg/core/type/DustType.kt
  core/src/main/java/com/gdg/core/type/LocationType.kt
  core/src/main/java/com/gdg/core/util/TimeFormatter.kt
  core/src/main/res/drawable/ic_congestion_green.xml
  core/src/main/res/drawable/ic_congestion_orange.xml
  core/src/main/res/drawable/ic_congestion_red.xml
  core/src/main/res/drawable/ic_congestion_yellow.xml
  core/src/main/res/drawable/ic_detail_marker.xml
  core/src/main/res/values/strings.xml
  domain/src/main/java/com/gdg/domain/entity/CongestionEntity.kt
  domain/src/main/java/com/gdg/domain/entity/WeatherEntity.kt
  feature/src/main/java/com/gdg/feature/detail/DetailRoute.kt
  feature/src/main/java/com/gdg/feature/detail/DetailSideEffect.kt
  feature/src/main/java/com/gdg/feature/detail/DetailViewModel.kt
  feature/src/main/java/res/mipmap-anydpi-v26/ic_launcher.xml
  feature/src/main/java/res/mipmap-anydpi-v26/ic_launcher_round.xml
  feature/src/main/java/res/mipmap-hdpi/ic_launcher.webp
  feature/src/main/java/res/mipmap-hdpi/ic_launcher_round.webp
  feature/src/main/java/res/mipmap-mdpi/ic_launcher.webp
  feature/src/main/java/res/mipmap-mdpi/ic_launcher_round.webp
  feature/src/main/java/res/mipmap-xhdpi/ic_launcher.webp
  feature/src/main/java/res/mipmap-xhdpi/ic_launcher_round.webp
  feature/src/main/java/res/mipmap-xxhdpi/ic_launcher.webp
  feature/src/main/java/res/mipmap-xxhdpi/ic_launcher_round.webp
  feature/src/main/java/res/mipmap-xxxhdpi/ic_launcher.webp
  feature/src/main/java/res/mipmap-xxxhdpi/ic_launcher_round.webp
  feature/src/main/java/res/values/colors.xml
  feature/src/main/java/res/values/strings.xml
  feature/src/main/java/res/values/themes.xml
  feature/src/main/res/drawable/ic_cloudy.xml
  feature/src/main/res/drawable/ic_detail_marker.xml
  feature/src/main/res/drawable/ic_launcher_background.xml
  feature/src/main/res/drawable/ic_launcher_foreground.xml
  feature/src/main/res/drawable/ic_pin.png
  feature/src/main/res/drawable/ic_rainy.xml
  feature/src/main/res/drawable/ic_snowy.xml
  feature/src/main/res/drawable/ic_sunny.xml
  feature/src/main/res/drawable/ic_sunny_cloudy.xml
  feature/src/main/res/values/dimens.xml
  feature/src/main/res/values/strings.xml
  feature/src/main/res/xml/backup_rules.xml
  feature/src/main/res/xml/data_extraction_rules.xml
Labels: :art: [UI], :maple_leaf: 가을

#9 [Feature/#7] : 캘린더 UI 구현
  core/src/main/java/com/gdg/core/designsystem/component/calendar/Calendar.kt
  core/src/main/java/com/gdg/core/util/CalendarUtils.kt
  core/src/main/java/com/gdg/core/util/TimeFormatter.kt
  core/src/main/res/drawable/calender_button_l.xml
  core/src/main/res/drawable/calender_button_r.xml
  core/src/main/res/values/strings.xml
  domain/build.gradle.kts
  domain/src/main/java/com/gdg/domain/entity/ScheduleEntity.kt
  feature/src/main/java/com/gdg/feature/calendar/CalendarRoute.kt
  feature/src/main/java/com/gdg/feature/calendar/CalendarViewModel.kt
  feature/src/main/res/drawable/ic_alert.png
  feature/src/main/res/values/strings.xml
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: :cat: 영서, :art: [UI]

#10 [Feature/#8] : 지도 UI 구현
  app/src/main/AndroidManifest.xml
  app/src/main/ic_logo-playstore.png
  app/src/main/java/com/gdg/crowdzero_android/main/MainScreen.kt
  app/src/main/java/com/gdg/crowdzero_android/navigation/SplashNavigation.kt
  app/src/main/res/drawable/ic_logo_background.xml
  app/src/main/res/mipmap-anydpi-v26/ic_logo.xml
  app/src/main/res/mipmap-anydpi-v26/ic_logo_round.xml
  app/src/main/res/mipmap-hdpi/ic_logo.webp
  app/src/main/res/mipmap-hdpi/ic_logo_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_logo_round.webp
  app/src/main/res/mipmap-mdpi/ic_logo.webp
  app/src/main/res/mipmap-mdpi/ic_logo_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_logo_round.webp
  app/src/main/res/mipmap-xhdpi/ic_logo.webp
  app/src/main/res/mipmap-xhdpi/ic_logo_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_logo_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_logo.webp
  app/src/main/res/mipmap-xxhdpi/ic_logo_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_logo_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_logo.webp
  app/src/main/res/mipmap-xxxhdpi/ic_logo_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_logo_round.webp
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  core/src/main/java/com/gdg/core/designsystem/component/calendar/Calendar.kt
  core/src/main/java/com/gdg/core/designsystem/component/chip/MapChip.kt
  core/src/main/java/com/gdg/core/designsystem/component/snackbar/BaseSnackBar.kt
  domain/src/main/java/com/gdg/domain/entity/PlaceEntity.kt
  domain/src/main/java/com/gdg/domain/entity/RoadEntity.kt
  feature/src/main/java/com/gdg/feature/map/MapRoute.kt
  feature/src/main/java/com/gdg/feature/map/MapViewModel.kt
  feature/src/main/java/com/gdg/feature/splash/SplashScreen.kt
  feature/src/main/res/drawable/ic_ban_marker.xml
  feature/src/main/res/drawable/ic_map_buildings.png
  feature/src/main/res/drawable/ic_map_marker.xml
  feature/src/main/res/drawable/ic_right_arrow.xml
  feature/src/main/res/drawable/ic_splash_buildings.png
  feature/src/main/res/values/strings.xml
Labels: :rabbit: 나현, :art: [UI]

#12 [Feature/#11] : 도로 통제 정보 모달 바텀 시트 구현
  app/src/main/java/com/gdg/crowdzero_android/main/MainScreen.kt
  app/src/main/java/com/gdg/crowdzero_android/navigation/SplashNavigation.kt
  feature/src/main/java/com/gdg/feature/map/MapRoute.kt
  feature/src/main/java/com/gdg/feature/map/MapViewModel.kt
  feature/src/main/java/com/gdg/feature/map/component/PlaceInfoCard.kt
  feature/src/main/java/com/gdg/feature/map/component/RoadInfoSheet.kt
  feature/src/main/res/values/strings.xml
Labels: :art: [UI], :maple_leaf: 가을

#18 [Feature/#17] : 날씨, 인구 혼잡도 api 연동 및 cleartext 이슈 해결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gdg/crowdzero_android/di/Qualifier.kt
  app/src/main/java/com/gdg/crowdzero_android/di/RetrofitModule.kt
  app/src/main/java/com/gdg/crowdzero_android/di/ServiceModule.kt
  data/src/main/java/com/gdg/data/datasource/CrowdZeroDataSource.kt
  data/src/main/java/com/gdg/data/datasourceimpl/CrowdZeroDataSourceImpl.kt
  data/src/main/java/com/gdg/data/repositoryimpl/CrowdZeroRepositoryImpl.kt
  data/src/main/java/com/gdg/data/service/CrowdZeroService.kt
  domain/src/main/java/com/gdg/domain/repository/CrowdZeroRepository.kt
  feature/src/main/java/com/gdg/feature/detail/DetailRoute.kt
  feature/src/main/java/com/gdg/feature/detail/DetailViewModel.kt
  feature/src/main/java/com/gdg/feature/map/MapRoute.kt
  feature/src/main/java/com/gdg/feature/map/MapViewModel.kt
  feature/src/main/res/values/strings.xml
Labels: :maple_leaf: 가을, :rotating_light: [FIX]

#20 [Feature/#15] 집회정보 API 연동
  data/src/main/java/com/gdg/data/datasource/CrowdZeroDataSource.kt
  data/src/main/java/com/gdg/data/datasourceimpl/CrowdZeroDataSourceImpl.kt
  data/src/main/java/com/gdg/data/dto/response/AssemblyResponseDto.kt
  data/src/main/java/com/gdg/data/dto/response/CongestionResponseDto.kt
  data/src/main/java/com/gdg/data/mapper/ResponseAssemblyDtoMapper.kt
  data/src/main/java/com/gdg/data/repositoryimpl/CrowdZeroRepositoryImpl.kt
  data/src/main/java/com/gdg/data/service/ApiKeyStorage.kt
  data/src/main/java/com/gdg/data/service/CrowdZeroService.kt
  domain/src/main/java/com/gdg/domain/entity/ScheduleEntity.kt
  domain/src/main/java/com/gdg/domain/repository/CrowdZeroRepository.kt
  feature/src/main/java/com/gdg/feature/calendar/CalendarRoute.kt
  feature/src/main/java/com/gdg/feature/calendar/CalendarViewModel.kt
  feature/src/main/res/values/strings.xml
Labels: :cat: 영서, :gem: [FEAT]

#19 [Feature/#16] 도로통제정보 API 연동
  data/src/main/java/com/gdg/data/datasource/CrowdZeroDataSource.kt
  data/src/main/java/com/gdg/data/datasourceimpl/CrowdZeroDataSourceImpl.kt
  data/src/main/java/com/gdg/data/dto/response/RoadResponseDto.kt
  data/src/main/java/com/gdg/data/mapper/ResponseRoadDtoMapper.kt
  data/src/main/java/com/gdg/data/repositoryimpl/CrowdZeroRepositoryImpl.kt
  data/src/main/java/com/gdg/data/service/CrowdZeroService.kt
  domain/src/main/java/com/gdg/domain/repository/CrowdZeroRepository.kt
  feature/src/main/java/com/gdg/feature/map/MapRoute.kt
  feature/src/main/java/com/gdg/feature/map/MapViewModel.kt
Labels: :rabbit: 나현, :gem: [FEAT]

#22 [Feature/#21] : 코드 리팩토링
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gdg/crowdzero_android/di/DataSourceModule.kt
  app/src/main/java/com/gdg/crowdzero_android/di/Qualifier.kt
  app/src/main/java/com/gdg/crowdzero_android/di/RepositoryModule.kt
  app/src/main/java/com/gdg/crowdzero_android/di/ServiceModule.kt
  app/src/main/java/com/gdg/crowdzero_android/main/MainScreen.kt
  app/src/main/java/com/gdg/crowdzero_android/navigation/CalendarNavigation.kt
  app/src/main/java/com/gdg/crowdzero_android/navigation/DetailNavigation.kt
  app/src/main/res/drawable/user_1.png
  app/src/main/res/drawable/user_2.png
  app/src/main/res/drawable/user_3.PNG
  app/src/main/res/values/strings.xml
  core/src/main/java/com/gdg/core/type/LocationType.kt
  core/src/main/res/drawable/ic_launcher_background.xml
  core/src/main/res/drawable/ic_launcher_foreground.xml
  data/src/main/java/com/gdg/data/datasource/ExampleDataSource.kt
  data/src/main/java/com/gdg/data/datasourceimpl/ExampleDataSourceImpl.kt
  data/src/main/java/com/gdg/data/dto/ExampleBaseResponse.kt
  data/src/main/java/com/gdg/data/dto/response/ExampleResponseDto.kt
  data/src/main/java/com/gdg/data/mapper/ResponseCongestionDtoMapper.kt
  data/src/main/java/com/gdg/data/mapper/ResponseExampleDtoMapper.kt
  data/src/main/java/com/gdg/data/mapper/ResponseWeatherDtoMapper.kt
  data/src/main/java/com/gdg/data/repositoryimpl/CrowdZeroRepositoryImpl.kt
  data/src/main/java/com/gdg/data/repositoryimpl/ExampleRepositoryImpl.kt
  data/src/main/java/com/gdg/data/service/ApiKeyStorage.kt
  data/src/main/java/com/gdg/data/service/ExampleService.kt
  domain/src/main/java/com/gdg/domain/entity/CongestionEntity.kt
  domain/src/main/java/com/gdg/domain/entity/ExampleEntity.kt
  domain/src/main/java/com/gdg/domain/entity/PlaceEntity.kt
  domain/src/main/java/com/gdg/domain/entity/ScheduleEntity.kt
  domain/src/main/java/com/gdg/domain/entity/WeatherEntity.kt
  domain/src/main/java/com/gdg/domain/repository/ExampleRepository.kt
  feature/src/main/java/com/gdg/feature/detail/DetailRoute.kt
  feature/src/main/java/com/gdg/feature/detail/DetailViewModel.kt
  feature/src/main/java/com/gdg/feature/example/ExampleItem.kt
  feature/src/main/java/com/gdg/feature/example/ExampleRoute.kt
  feature/src/main/java/com/gdg/feature/example/ExampleSideEffect.kt
  feature/src/main/java/com/gdg/feature/example/ExampleState.kt
  feature/src/main/java/com/gdg/feature/example/ExampleViewModel.kt
  feature/src/main/java/com/gdg/feature/map/MapRoute.kt
  feature/src/main/java/com/gdg/feature/map/MapSideEffect.kt
  feature/src/main/java/com/gdg/feature/map/MapViewModel.kt
  feature/src/main/java/com/gdg/feature/map/component/PlaceInfoCard.kt
  feature/src/main/java/com/gdg/feature/splash/SplashScreen.kt
  feature/src/main/res/drawable/ic_launcher_background.xml
  feature/src/main/res/drawable/ic_launcher_foreground.xml
  feature/src/main/res/values/strings.xml
Labels: :recycle: [REFACTOR], :maple_leaf: 가을

#24 [Feature/#23] : 코드 리팩토링
  core/src/main/java/com/gdg/core/designsystem/component/calendar/Calendar.kt
  feature/src/main/java/com/gdg/feature/calendar/CalendarRoute.kt
  feature/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: :cat: 영서, :recycle: [REFACTOR]

#27 [Feature/#26] 리드미 수정
  README.md
Labels: :rabbit: 나현, :page_facing_up: [DOCS]

#28 [Feature/#25] : 혼잡도, 날씨, 미세먼지 스케일 이슈 해결
  core/src/main/java/com/gdg/core/designsystem/theme/Color.kt
  core/src/main/java/com/gdg/core/type/DustConditionType.kt
  core/src/main/res/values/strings.xml
  feature/src/main/java/com/gdg/feature/calendar/CalendarRoute.kt
  feature/src/main/java/com/gdg/feature/calendar/component/CalendarInfoBox.kt
  feature/src/main/java/com/gdg/feature/detail/DetailRoute.kt
  feature/src/main/java/com/gdg/feature/detail/component/CongestionItem.kt
  feature/src/main/java/com/gdg/feature/detail/component/WeatherItem.kt
  feature/src/main/java/com/gdg/feature/map/component/PlaceInfoCard.kt
Labels: :maple_leaf: 가을, :rotating_light: [FIX]
